import {useEffect,useRef,useState} from 'react';
import {fields,filterRows,summary} from '@hazcom/authoring';

export const navigation=['Management Home','Work Areas','Chemical Library','Workers','Assignments & Training','Reports & Export','Company & Access Administration'];
type Props={company:{id:string;name:string;contact_email:string;role:string};open:()=>Promise<any>;administration?:{update:(name:string,email:string)=>Promise<void>;members:()=>Promise<any[]>;setMember:(value:any)=>Promise<void>}};
const labels:Record<string,string>={name:'Name',location:'Location',poc_name:'POC name',poc_email:'POC email',poc_phone_number:'POC phone',description:'Description',product_name:'Product name',chemical_names:'Chemical names',cas_numbers:'CAS numbers',manufacturer:'Manufacturer',sds_date:'SDS date',email:'Email',phone:'Phone',quantity:'Quantity',storage_location:'Storage location',added_date:'Added date',assigned_date:'Assigned date',ended_date:'Ended date',verified_at:'Verification date',review_date:'Review date',training_date:'Training date',work_area_id:'Work Area',chemical_product_id:'Chemical Product',worker_id:'Worker',work_area_assignment_id:'Assignment'};
const eventKinds=['sds_verification','hazcom_review','training_event'];
const today=()=>new Date().toISOString().slice(0,10);
const title=(r:any)=>r?.name??r?.product_name??r?.id??'Missing record';
export default function AuthoringWorkspace({company,open,administration}:Props){
 const [service,setService]=useState<any>(null),[data,setData]=useState<any>(null),[screen,setScreen]=useState('Management Home'),[filter,setFilter]=useState<any>({}),[selected,setSelected]=useState<string|null>(null);
 const [form,setForm]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[members,setMembers]=useState<any[]>([]),[preview,setPreview]=useState<string|null>(null);
 const running=useRef(false),alive=useRef(true),formRef=useRef<any>(null);formRef.current=form;
 useEffect(()=>{alive.current=true;let current=true;open().then(async s=>{const d=await s.snapshot();if(current){setService(s);setData(d);}}).catch(e=>{if(current)setError(String(e.message??e));});return()=>{current=false;alive.current=false;};},[open]);
 useEffect(()=>{const guard=(e:Event)=>{if(formRef.current){e.preventDefault();setNotice('Save or cancel the open form before leaving.');}};const unload=(e:BeforeUnloadEvent)=>{if(formRef.current){e.preventDefault();e.returnValue='';}};window.addEventListener('hazcom:before-navigation',guard);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('hazcom:before-navigation',guard);window.removeEventListener('beforeunload',unload);};},[]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 const move=(next:string,f:any={})=>{if(form){setNotice('Save or cancel the open form before leaving.');return;}setScreen(next);setSelected(null);setFilter(f);setError('');setNotice('');setPreview(null);};
 async function action(fn:()=>Promise<any>,message='Saved in local draft workspace.'){
  if(running.current)return;running.current=true;setBusy(true);setError('');
  try{await fn();const next=await service.snapshot();if(alive.current){setData(next);setNotice(message);}}
  catch(e){if(alive.current)setError(e instanceof Error?e.message:String(e));}
  finally{running.current=false;if(alive.current)setBusy(false);}
 }
 const kind=screen==='Work Areas'?'work_area':screen==='Chemical Library'?'chemical_product':screen==='Workers'?'worker':'work_area_assignment';
 const records=data?filterRows(kind,data[kind],kind==='worker'?{...filter,workAreaId:''}:filter).filter((w:any)=>{if(kind!=='worker')return true;const rows=data.work_area_assignment.filter((a:any)=>a.worker_id===w.id&&a.active&&(!filter.workAreaId||a.work_area_id===filter.workAreaId));return (!filter.workAreaId||rows.length)&&(!filter.workerTraining||(filter.workerTraining==='assigned'?rows.length:rows.some((a:any)=>a.status!=='current')));}):[],record=data?.[kind].find((r:any)=>r.id===selected);
 const name=(k:string,id:string)=>title(data?.[k].find((r:any)=>r.id===id));
 function edit(k:string,row:any=null,defaults:any={}){setError('');setNotice('');setForm({kind:k,id:row?.id??crypto.randomUUID(),editing:!!row,values:row?{...row}:Object.fromEntries(fields[k as keyof typeof fields].map((key:string)=>[key,key.endsWith('_date')||key==='verified_at'?today():''])),...{defaults}});if(!row)setForm((f:any)=>({...f,values:{...f.values,ended_date:'',...defaults}}));}
 async function save(){await action(async()=>{if(form.kind==='company'){await administration!.update(form.values.name,form.values.email);}else if(form.kind==='membership'){await administration!.setMember({...form.values,active:form.values.active!=='false',workerId:form.values.workerId||null});setMembers(await administration!.members());}else if(form.editing)await service.update(form.kind,form.id,form.values);else await service.create(form.kind,form.values,form.id);setForm(null);});}
 const badge=(state:string)=><span className={`badge ${state}`}>{state==='approaching'?'Approaching due':state==='required'?'Required':state==='overdue'?'Overdue':'Current'}</span>;
 const eventButton=(k:string,parent:string,id:string)=><button disabled={busy||!!form} onClick={()=>edit(k,null,{[parent]:id})}>{k==='training_event'?'Record training':k==='hazcom_review'?'Record HAZCOM review':'Verify SDS current'}</button>;
 const history=(k:string,parent:string,id:string,date:string)=><ul>{data[k].filter((e:any)=>e[parent]===id).sort((a:any,b:any)=>b[date].localeCompare(a[date])).map((e:any)=><li key={e.id}>{e[date]} <small>Recorded event · {e.id.slice(0,8)}</small></li>)}</ul>;
 const assignmentTable=(rows:any[])=><div className="table-wrap"><table><thead><tr><th>Worker / Work Area</th><th>Assigned / Ended</th><th>Training required since</th><th>Latest training</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td>{name('worker',a.worker_id)}<br/>{name('work_area',a.work_area_id)}</td><td>{a.assigned_date}<br/>{a.ended_date??'Open'}</td><td>{a.training_required_since}</td><td>{a.latest??'No training'}</td><td>{a.deleted_at?'In trash':badge(a.status)}</td><td><button disabled={busy||!!form||!!a.deleted_at} onClick={()=>edit('work_area_assignment',a)}>Edit / end</button>{!a.deleted_at&&eventButton('training_event','work_area_assignment_id',a.id)}{a.deleted_at&&<button disabled={busy} onClick={()=>void action(()=>service.trash('work_area_assignment',a.id,true))}>Restore</button>}</td></tr>)}</tbody></table>{!rows.length&&<p>No assignments match this view.</p>}</div>;
 if(!data)return <main><h1>Opening {company.name}</h1>{error?<p role="alert">{error}</p>:<p role="status">Loading local authoring workspace…</p>}</main>;
 const totals=summary(data);
 const widgets:[string,number,string,any][]=[['Work Areas',totals.areas,'Work Areas',{}],['Chemical Products',totals.chemicals,'Chemical Library',{}],['Workers',totals.workers,'Workers',{}],['Active assignments',totals.assignments,'Assignments & Training',{assignmentState:'active'}],['SDS verifications overdue',totals.sdsOverdue,'Chemical Library',{status:'overdue'}],['SDS approaching due',totals.sdsApproaching,'Chemical Library',{status:'approaching'}],['SDS never verified',totals.sdsRequired,'Chemical Library',{status:'required'}],['HAZCOM reviews overdue',totals.reviewsOverdue,'Work Areas',{status:'overdue'}],['Reviews approaching due',totals.reviewsApproaching,'Work Areas',{status:'approaching'}],['Areas never reviewed',totals.reviewsRequired,'Work Areas',{status:'required'}],['Assignments needing training',totals.training,'Assignments & Training',{status:'needs-training',assignmentState:'active'}],['Products without draft SDS',totals.missingSds,'Chemical Library',{status:'missing-sds'}]];
 return <main className="authoring"><header><h1>{screen}</h1><p>{company.name} · Local draft authoring</p></header><nav className="workspace-nav" aria-label="Management screens">{navigation.map(n=><button key={n} className={n===screen?'active':''} onClick={()=>move(n)}>{n}</button>)}</nav>
  {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}{busy&&<p role="status">Saving…</p>}
  {form&&<section className="panel editor" aria-label="Record form"><h2>{form.kind==='company'?'Company settings':form.kind==='membership'?'Company membership':`${form.editing?'Edit':'Add'} ${form.kind.replaceAll('_',' ')}`}</h2><form onSubmit={e=>{e.preventDefault();void save();}}><div className="form-grid">
   {(form.kind==='company'?['name','email']:form.kind==='membership'?['uid','role','active','workerId']:[...fields[form.kind as keyof typeof fields],...(!form.editing?Object.keys(form.defaults):[])]).map((key:string)=>{
    const relation=key.endsWith('_id')?key.slice(0,-3):key==='workerId'?'worker':null;
    const options=relation&&data[relation]?data[relation].filter((r:any)=>!r.deleted_at):null;
    const update=(value:string)=>setForm({...form,values:{...form.values,[key]:value}});
    return <label key={key}>{labels[key]??({uid:'Existing Firebase Account UID',role:'Company role',active:'Membership active',workerId:'Linked Worker (optional)'} as any)[key]??key}{options?<select required={key!=='workerId'} value={form.values[key]??''} onChange={e=>update(e.target.value)}><option value="">Choose…</option>{options.map((r:any)=><option key={r.id} value={r.id}>{relation==='work_area_assignment'?`${name('worker',r.worker_id)} / ${name('work_area',r.work_area_id)}`:title(r)}</option>)}</select>:key==='role'||key==='active'?<select value={form.values[key]} onChange={e=>update(e.target.value)}>{(key==='role'?['member','manager','administrator']:['true','false']).map(v=><option key={v}>{v}</option>)}</select>:key==='description'?<textarea value={form.values[key]??''} onChange={e=>update(e.target.value)} maxLength={8000}/>:<input value={form.values[key]??''} type={key.endsWith('_date')||key==='verified_at'?'date':key.includes('email')?'email':'text'} readOnly={form.editing&&['added_date','assigned_date'].includes(key)} maxLength={1000} onChange={e=>update(e.target.value)} required={['name','product_name','manufacturer','sds_date','assigned_date','added_date','quantity','storage_location','verified_at','review_date','training_date','uid'].includes(key)}/>}</label>;
   })}</div>{eventKinds.includes(form.kind)&&<p>Completion records are append-only. Check the date before saving.</p>}<div className="actions"><button disabled={busy}>Save</button><button type="button" disabled={busy} onClick={()=>{setForm(null);setNotice('Form cancelled.');}}>Cancel</button></div></form></section>}
  {screen==='Management Home'&&<><section className="grid">{widgets.map(([label,value,next,f])=><button className="metric" key={label} onClick={()=>move(next,f)}><span>{label}</span><strong>{value}</strong></button>)}</section><section className="panel"><h2>Recent local activity</h2>{data.activity.length?<ul>{data.activity.map((a:any)=><li key={a.id}>{a.changed_at.slice(0,16).replace('T',' ')} · {a.action} {a.record_type.replaceAll('_',' ')}</li>)}</ul>:<p>No local changes recorded yet.</p>}</section></>}
  {['Work Areas','Chemical Library','Workers','Assignments & Training'].includes(screen)&&<>
   <section className="panel"><div className="toolbar"><label>Search<input value={filter.query??''} onChange={e=>{setFilter({...filter,query:e.target.value});setSelected(null);}} placeholder={kind==='chemical_product'?'Product, chemical name or CAS':'Search records'}/></label><label>View<select value={filter.trash?'trash':'active'} onChange={e=>{setFilter({...filter,trash:e.target.value==='trash'});setSelected(null);}}><option value="active">Active records</option><option value="trash">Trash</option></select></label>
    {kind!=='worker'&&<label>Status<select value={filter.status??''} onChange={e=>setFilter({...filter,status:e.target.value})}><option value="">All statuses</option><option value="current">Current</option><option value="required">Required / never completed</option><option value="overdue">Overdue</option>{kind==='work_area_assignment'?<option value="needs-training">Needs training</option>:<option value="approaching">Approaching due</option>}{kind==='chemical_product'&&<option value="missing-sds">Missing draft SDS</option>}</select></label>}
    {kind==='chemical_product'&&<label>Manufacturer<select value={filter.manufacturer??''} onChange={e=>setFilter({...filter,manufacturer:e.target.value})}><option value="">All manufacturers</option>{Array.from(new Set<string>(data.chemical_product.map((r:any)=>r.manufacturer))).sort().map(m=><option key={m}>{m}</option>)}</select></label>}
    {['worker','work_area_assignment'].includes(kind)&&<><label>Work Area<select value={filter.workAreaId??''} onChange={e=>setFilter({...filter,workAreaId:e.target.value})}><option value="">All Work Areas</option>{data.work_area.filter((r:any)=>!r.deleted_at).map((r:any)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{kind==='worker'?<label>Training<select value={filter.workerTraining??''} onChange={e=>setFilter({...filter,workerTraining:e.target.value})}><option value="">All Workers</option><option value="required">Needs training</option><option value="assigned">Actively assigned</option></select></label>:<><label>Worker<select value={filter.workerId??''} onChange={e=>setFilter({...filter,workerId:e.target.value})}><option value="">All Workers</option>{data.worker.filter((r:any)=>!r.deleted_at).map((r:any)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Assignment<select value={filter.assignmentState??''} onChange={e=>setFilter({...filter,assignmentState:e.target.value})}><option value="">Active and historical</option><option value="active">Active</option><option value="ended">Ended / inactive</option></select></label></>}</>}
    <button disabled={busy||!!form} onClick={()=>edit(kind,null,kind==='work_area_assignment'?{work_area_id:'',worker_id:''}:{})}>Add {kind==='work_area_assignment'?'assignment':kind.replaceAll('_',' ')}</button><button onClick={()=>{setFilter({});setSelected(null);}}>Clear filters</button></div>
    {kind==='work_area_assignment'?assignmentTable(records):<div className="table-wrap"><table><thead><tr><th>Record</th><th>{kind==='work_area'?'Location / Review':kind==='chemical_product'?'Manufacturer / SDS':'Contact'}</th><th>Action</th></tr></thead><tbody>{records.map((r:any)=><tr key={r.id}><td>{title(r)}{r.deleted_at&&<strong> · In trash</strong>}</td><td>{kind==='worker'?r.email??'No email':<>{kind==='work_area'?r.location:r.manufacturer} {badge(r.status)}{kind==='chemical_product'&&!r.hasSds&&<span className="badge required">No draft SDS</span>}</>}</td><td><button disabled={!!form} onClick={()=>{setSelected(r.id);setPreview(null);}}>View details</button></td></tr>)}</tbody></table>{!records.length&&<p>No records match. Create a record or clear filters.</p>}</div>}
   </section>
   {record&&kind!=='work_area_assignment'&&<section className="panel detail"><h2>{title(record)}</h2><dl>{fields[kind as keyof typeof fields].map((k:string)=><div key={k}><dt>{labels[k]}</dt><dd>{record[k]||'—'}</dd></div>)}</dl><div className="actions"><button disabled={busy||!!form||!!record.deleted_at} onClick={()=>edit(kind,record)}>Edit</button><button disabled={busy||!!form} onClick={()=>void action(()=>service.trash(kind,record.id,!!record.deleted_at),record.deleted_at?'Restored. Review related records in Trash.':'Moved to Trash. History and local SDS files retained.')}>{record.deleted_at?'Restore':'Move to Trash'}</button></div>
    {kind==='work_area'&&<><h3>HAZCOM review</h3><p>{badge(record.status)} Latest: {record.latest??'Never'} · Next due: {record.due??'Required now'}</p>{!record.deleted_at&&eventButton('hazcom_review','work_area_id',record.id)}{history('hazcom_review','work_area_id',record.id,'review_date')}<h3>Chemicals in this area</h3>{!record.deleted_at&&<button disabled={busy||!!form} onClick={()=>edit('work_area_product',null,{work_area_id:record.id,chemical_product_id:''})}>Add Chemical to Work Area</button>}<ul>{data.work_area_product.filter((r:any)=>r.work_area_id===record.id).map((r:any)=>{const chemical=data.chemical_product.find((c:any)=>c.id===r.chemical_product_id);return <li key={r.id}>{title(chemical)} · {r.quantity} · {r.storage_location} · added {r.added_date} {r.deleted_at?'(removed)':<>{badge(chemical?.status)} {!chemical?.hasSds&&'Missing draft SDS'}</>} <button disabled={busy||!!form||!!r.deleted_at||!!record.deleted_at} onClick={()=>edit('work_area_product',r)}>Edit placement</button><button disabled={busy||!!form||!!record.deleted_at} onClick={()=>void action(()=>service.trash('work_area_product',r.id,!!r.deleted_at))}>{r.deleted_at?'Restore placement':'Remove placement'}</button></li>;})}</ul><h3>Assignments and training</h3>{!record.deleted_at&&<button disabled={busy||!!form} onClick={()=>edit('work_area_assignment',null,{work_area_id:record.id,worker_id:''})}>Assign Worker</button>}{assignmentTable(data.work_area_assignment.filter((a:any)=>a.work_area_id===record.id))}</>}
    {kind==='chemical_product'&&<><h3>Local draft SDS</h3><p>Managed local PDFs are draft attachments. They are not published until an explicit publication completes.</p>{!record.deleted_at&&<label>Choose / replace PDF<input type="file" accept="application/pdf,.pdf" disabled={busy||!!form} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void action(async()=>{if(file.size>5*1024*1024)throw Error('Choose a PDF no larger than 5 MiB');await service.importSds(record.id,new Uint8Array(await file.arrayBuffer()),file.name);});}}/></label>}<ul>{data.attachments.filter((a:any)=>a.owner_id===record.id).map((a:any)=><li key={a.id}>{a.slot_key==='sds'?'Current draft':'Retained history'} · {a.original_filename} · {a.size_bytes} bytes <small>{a.sha256??'Hash verified at publication'}</small><button disabled={busy} onClick={()=>void action(async()=>{const bytes=await service.readSds(record.id,a.id);setPreview(URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})));},'SDS integrity verified.')}>View PDF</button>{a.slot_key==='sds'&&!record.deleted_at&&<button disabled={busy||!!form} onClick={()=>void action(()=>service.unlinkSds(record.id))}>Unlink draft SDS</button>}</li>)}</ul>{preview&&<iframe title="Local SDS PDF" src={preview} className="pdf-preview"/>}<h3>SDS verification</h3><p>{badge(record.status)} Latest: {record.latest??'Never'} · Next due: {record.due??'Required now'}</p>{!record.deleted_at&&eventButton('sds_verification','chemical_product_id',record.id)}{history('sds_verification','chemical_product_id',record.id,'verified_at')}<h3>Work Areas using this product</h3><ul>{data.work_area_product.filter((r:any)=>r.chemical_product_id===record.id).map((r:any)=><li key={r.id}>{name('work_area',r.work_area_id)} · {r.quantity} · {r.deleted_at?'Removed':'Active'}</li>)}</ul></>}
    {kind==='worker'&&<><p>This is a business Worker record. A Firebase Account is linked separately by a Company Administrator.</p><h3>Active and historical assignments</h3>{!record.deleted_at&&<button disabled={busy||!!form} onClick={()=>edit('work_area_assignment',null,{work_area_id:'',worker_id:record.id})}>Assign to Work Area</button>}{assignmentTable(data.work_area_assignment.filter((a:any)=>a.worker_id===record.id))}<h3>Training history</h3>{data.work_area_assignment.filter((a:any)=>a.worker_id===record.id).map((a:any)=><div key={a.id}><h4>{name('work_area',a.work_area_id)}</h4>{history('training_event','work_area_assignment_id',a.id,'training_date')}</div>)}</>}
   </section>}
  </>}
  {screen==='Reports & Export'&&<section className="panel"><h2>Publication and reports status</h2><p>The local draft serializer and scalable publication service are implemented and automated-tested. This screen does not publish changes.</p><p>Formatted reports, PDF exports and a publication control panel are planned for later slices.</p><p>Current Company: {totals.areas} Work Areas, {totals.chemicals} Chemical Products, {totals.workers} Workers. Resolve warnings on Management Home before publication.</p></section>}
  {screen==='Company & Access Administration'&&<section className="panel"><h2>Company settings and access</h2><p>{company.name} · {company.contact_email}</p><p>Your role: {company.role}. Membership and settings changes use the existing trusted Firebase Functions.</p>{company.role!=='administrator'?<p>Company settings and access administration require an Administrator. Managers retain HazCom authoring access.</p>:administration?<><button disabled={busy||!!form} onClick={()=>setForm({kind:'company',values:{name:company.name,email:company.contact_email}})}>Edit Company</button><button disabled={busy||!!form} onClick={()=>void action(async()=>setMembers(await administration.members()),'Memberships refreshed.')}>Load memberships</button><button disabled={busy||!!form} onClick={()=>setForm({kind:'membership',values:{uid:'',role:'member',active:'true',workerId:''}})}>Add / update membership</button><ul>{members.map(m=><li key={m.uid}>{m.uid} · {m.role} · {m.active?'Active':'Inactive'} · Linked Worker: {m.workerId?name('worker',m.workerId):'None'}</li>)}</ul><p>The Account must already exist. Worker linking uses published Worker records; a draft-only Worker must be published first. No billing or Account creation is performed here.</p></>:<p>Cloud administration is unavailable in this local test harness.</p>}</section>}
 </main>;
}
