import {useEffect,useMemo,useState} from 'react';
import {chemicalInventoryReport,complianceStatusReport,trainingStatusReport,reportCsv,summary} from '@hazcom/authoring';
import {diagnostics} from './diagnostics/session';
type Props={company:{id:string;name:string};data:any};type Report='chemicalInventory'|'complianceStatus'|'trainingStatus';
const displayStatus=(value:string)=>value?value==='approaching'?'Approaching due':value[0].toUpperCase()+value.slice(1):'—';
const names:Record<Report,string>={chemicalInventory:'Chemical Inventory',complianceStatus:'Compliance Status',trainingStatus:'Training Status'};
export default function ReportsPanel({company,data}:Props){
 const [report,setReport]=useState<Report>('chemicalInventory'),[workAreaId,setWorkAreaId]=useState(''),[query,setQuery]=useState(''),[history,setHistory]=useState(false);const totals=useMemo(()=>summary(data),[data]);
 const inventory=useMemo(()=>chemicalInventoryReport(data,{workAreaId,query}),[data,workAreaId,query]),compliance=useMemo(()=>complianceStatusReport(data),[data]),training=useMemo(()=>trainingStatusReport(data,{includeHistorical:history}),[data,history]);const rows=report==='chemicalInventory'?inventory:report==='complianceStatus'?compliance:training;
 useEffect(()=>{diagnostics.emit('report.open','opened',{entity:report,count:rows.length});},[report]);
 function exportCsv(){try{const csv=reportCsv(report,rows),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`hazcom-${report.replace(/[A-Z]/g,value=>'-'+value.toLowerCase())}.csv`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);diagnostics.emit('report.export','succeeded',{entity:report,count:rows.length,bytes:blob.size});}catch(error){diagnostics.emit('report.export','failed',{entity:report,reason:'OPERATION_FAILED'});throw error;}}
 return <>
  <section className="panel" aria-label="Company HazCom Summary"><h2>Company HazCom Summary</h2><p>{company.name} · current local workspace</p><div className="grid report-summary"><div className="metric"><span>Active Work Areas</span><strong>{totals.areas}</strong></div><div className="metric"><span>Active Chemical Products</span><strong>{totals.chemicals}</strong></div><div className="metric"><span>Active Workers</span><strong>{totals.workers}</strong></div><div className="metric"><span>Active assignments</span><strong>{totals.assignments}</strong></div><div className="metric"><span>Products missing SDS</span><strong>{totals.missingSds}</strong></div><div className="metric"><span>SDS verification overdue</span><strong>{totals.sdsOverdue}</strong></div><div className="metric"><span>Work Area reviews overdue</span><strong>{totals.reviewsOverdue}</strong></div><div className="metric"><span>Assignments needing training</span><strong>{totals.training}</strong></div></div></section>
  <section className="panel" aria-label="Operational Reports"><div className="toolbar"><label>Operational report<select aria-label="Operational report" value={report} onChange={event=>setReport(event.target.value as Report)}>{Object.entries(names).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{report==='chemicalInventory'&&<><label>Work Area<select value={workAreaId} onChange={event=>setWorkAreaId(event.target.value)}><option value="">All active Work Areas</option>{data.work_area.filter((row:any)=>!row.deleted_at).sort((a:any,b:any)=>a.name.localeCompare(b.name)).map((row:any)=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Search<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Product, manufacturer or CAS"/></label></>}{report==='trainingStatus'&&<label className="report-checkbox"><input type="checkbox" checked={history} onChange={event=>setHistory(event.target.checked)}/>Include ended assignments</label>}<button onClick={exportCsv}>Export {names[report]} CSV</button></div>
   {report==='chemicalInventory'&&<div role="region" aria-label="Chemical Inventory report"><h2>Chemical Inventory by Work Area</h2><p>Active placements from this local Company workspace.</p><div className="table-wrap"><table><thead><tr><th>Work Area</th><th>Chemical Product</th><th>Manufacturer / CAS</th><th>Quantity / Storage</th><th>SDS</th><th>Verification</th></tr></thead><tbody>{inventory.map((row:any,index:number)=><tr key={`${row.workAreaId}:${row.productName}:${row.storageLocation}:${index}`}><td>{row.workArea}<br/><small>{row.workAreaLocation||'No location recorded'}</small></td>{row.empty?<td colSpan={5}>No active Chemical Products</td>:<><td>{row.productName}</td><td>{row.manufacturer}<br/><small>{row.casNumbers||'No CAS recorded'}</small></td><td>{row.quantity}<br/><small>{row.storageLocation}</small></td><td>{row.sdsPresent}<br/><small>{row.sdsDate||'No date recorded'}</small></td><td>{displayStatus(row.sdsVerificationStatus)}</td></>}</tr>)}</tbody></table>{!inventory.length&&<p>No active inventory matches these filters.</p>}</div></div>}
   {report==='complianceStatus'&&<div role="region" aria-label="Compliance Status report"><h2>Compliance Status</h2><p>Tracked SDS verification and HazCom review status. This report does not make a regulatory compliance determination.</p><div className="table-wrap"><table><thead><tr><th>Category</th><th>Item</th><th>Context</th><th>SDS present</th><th>Most recent event</th><th>Next due</th><th>Tracked status</th></tr></thead><tbody>{compliance.map((row:any,index:number)=><tr key={`${row.category}:${row.item}:${index}`}><td>{row.category}</td><td>{row.item}</td><td>{row.context||'—'}</td><td>{row.sdsPresent||'—'}</td><td>{row.latest||'Never'}</td><td>{row.due||'Required now'}</td><td>{displayStatus(row.status)}</td></tr>)}</tbody></table>{!compliance.length&&<p>No active Chemical Products or Work Areas.</p>}</div></div>}
   {report==='trainingStatus'&&<div role="region" aria-label="Training Status report"><h2>Training Status</h2><p>{history?'Active and ended':'Active'} Work Area Assignments from this local Company workspace.</p><div className="table-wrap"><table><thead><tr><th>Worker</th><th>Work Area</th><th>Assigned / ended</th><th>Training required since</th><th>Most recent training</th><th>Status</th></tr></thead><tbody>{training.map((row:any,index:number)=><tr key={`${row.worker}:${row.workArea}:${row.assignedDate}:${index}`}><td>{row.worker}</td><td>{row.workArea}</td><td>{row.assignedDate}<br/><small>{row.endedDate||'Active'}</small></td><td>{row.trainingRequiredSince||'—'}</td><td>{row.latestTraining||'Never'}</td><td>{displayStatus(row.status)}</td></tr>)}</tbody></table>{!training.length&&<p>No assignments match this report.</p>}</div></div>}
  </section>
 </>;
}
