import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,writeFile,unlink,stat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {nodeSqlite} from '../../packages/sync/src/node.js';
import {REPLICA_SCHEMA_SQL} from '../../packages/sync/src/sqlite.js';
import {collectWorkspaces} from './workspaces.mjs';
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
test('workspace diagnostics are read-only, distinguish remembered selection and detect invalid restores',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'hazcom-workspace-diagnostic-'));
 const active=path.join(root,'restored-workspaces','copy-a','active');await mkdir(active,{recursive:true});
 const plan=JSON.parse(await readFile(new URL('../../apps/windows/test/native-restore-plan.json',import.meta.url),'utf8'));
 const migrations=await Promise.all(['003_authoring.sql','004_bulk_sds_import.sql','005_bulk_sds_extraction.sql'].map(name=>readFile(new URL('../../database/migrations/'+name,import.meta.url),'utf8')));
 const databaseFile=path.join(active,'workspace.db'),sql=nodeSqlite(databaseFile,REPLICA_SCHEMA_SQL+migrations.join('\n'));
 await sql.batch(plan.statements);sql.close();
 const fileRoot=path.join(active,'attachments',plan.companyId);await mkdir(fileRoot,{recursive:true});
 for(const file of plan.files)await writeFile(path.join(fileRoot,file.attachmentId+'.pdf'),new Uint8Array(file.bytes));
 await writeFile(path.join(active,'restore-manifest.json'),JSON.stringify(plan.manifest));
 await writeFile(path.join(active,'restore-files.json'),JSON.stringify(plan.files.map(({attachmentId,ownerId,sizeBytes,sha256})=>({attachmentId,ownerId,sizeBytes,sha256}))));
 const registryFile=path.join(root,'workspace-registry.db'),registry=new DatabaseSync(registryFile);
 registry.exec('CREATE TABLE selections(account_id TEXT,company_id TEXT,workspace_id TEXT)');
 registry.prepare('INSERT INTO selections VALUES (?,?,?)').run('account',plan.companyId,'restored-copy-a');
 registry.prepare('INSERT INTO selections VALUES (?,?,?)').run('other-account',plan.companyId,'restored-deleted');registry.close();
 const before=hash(await readFile(databaseFile)),registryBefore=hash(await readFile(registryFile));
 const options={appDataRoot:root,sourceMigrationDir:path.resolve('database/migrations')};
 let report=await collectWorkspaces(options);
 assert.equal(report.restoredCount,1);assert.equal(report.availableRestoredCount,1);
 assert.equal(report.activeWorkspaceId,null);assert.equal(report.workspaces[0].publication.supported,true);assert.equal(report.workspaces[0].publication.enabled,null);
 assert.equal(report.workspaces[0].verifiedSds,20);assert.equal(report.rememberedSelections[1].available,false);
 assert.equal(hash(await readFile(databaseFile)),before);assert.equal(hash(await readFile(registryFile)),registryBefore);
 assert.equal(JSON.stringify(report).includes('bytes'),false);
 await writeFile(path.join(fileRoot,plan.files[0].attachmentId+'.pdf'),'%PDF-corrupted');
 report=await collectWorkspaces(options);assert.equal(report.workspaces[0].status,'FAIL');assert.match(report.workspaces[0].reason,/INTEGRITY/);
 await unlink(databaseFile);report=await collectWorkspaces(options);assert.equal(report.availableRestoredCount,0);
 await assert.rejects(stat(databaseFile),{code:'ENOENT'});
});
